# Search Results Page locators
prod_url = "http://citymd.com"
stage_url = "https://citymdstg.prod.acquia-sites.com/"
qa_url = "https://citymdqa.prod.acquia-sites.com/"
dev_url = "https://citymddev.prod.acquia-sites.com/"
search_term = "Vaccination"
remote_url = "http://macchu77:b365eb9a-f746-4ded-9189-bb1ce964f30d@ondemand.saucelabs.com:80/wd/hub"
chrome_desired_capabilities = "build:mactest1,platform:macOS 12,browserName:chrome,version:latest"
safari_desired_capabilities = "build:mactest2,platform:macOS 12,browserName:safari,version:latest"
firefox_desired_capabilities = "build:mactest2,platform:Windows 11,browserName:firefox,version:latest"